### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alphapapa** [dw-github-mirror/org-superstar-mode#1]
Hi there,

I saw your post on the Org mailing list.  I was afraid that you weren't going to share the link to the repo!  This looks great!  Nice name, too.  ;)

Quick suggestion: the symbol prefixes should generally match the package name (e.g. MELPA requires this), so `org-sstar` should be `org-superstar`.

You may find this helpful in testing and linting: https://github.com/alphapapa/makem.sh

Can't wait to see this on MELPA!

**Comment by dw-github-mirror** [comment]
Hi, 
I am aware of that convention, it's also the major bugbear for flycheck for the time being, so I am considering either a shorter package name or just accepting the length of function names.

I am currently working on a few more tests, though I am looking into packagine and testing facilities like cask or makem, which I didn't know of up until now.  Thanks!

I am currently getting ready to patch a few things along with styling issues, stay tuned!

**Comment by dw-github-mirror** [comment]
Naming convention is fixed, along with all complains flycheck has thrown at me (including checkdock and package).
